import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve, join } from 'path';
import { homedir } from 'os';
import { existsSync, readFileSync } from 'fs';

// Generated by `npx office-addin-dev-certs install` — required because Word
// only loads add-ins served over HTTPS, including localhost.
const certDir = join(homedir(), '.office-addin-dev-certs');
const httpsConfig = existsSync(join(certDir, 'localhost.crt'))
  ? {
      cert: readFileSync(join(certDir, 'localhost.crt')),
      key: readFileSync(join(certDir, 'localhost.key')),
    }
  : undefined;

export default defineConfig({
  plugins: [react()],
  root: 'src',
  build: {
    outDir: '../dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        taskpane: resolve(__dirname, 'src/taskpane.html'),
        commands: resolve(__dirname, 'src/commands.html'),
      },
    },
  },
  server: {
    port: 3002,
    https: httpsConfig,
    cors: true,
    host: true,
  },
});
